### ISSUE TITLE
cactus be broke

### ISSUE THREAD

**Issue by VoteforShifu** [xDraxxis/XMCDungeons#13]
it is V O I D colored and not cube

**Comment by Pxie1** [comment]
but void is kinda nice doe

**Comment by Pxie1** [comment]
wrong object / entity for cactus block when placed. Is fine in hand and in inventory.

Block one does not have texture and is a rather voidy boi

**Comment by xDraxxis** [comment]
how

**Comment by xDraxxis** [comment]
:worksonmypc:
