### ISSUE TITLE
Things to remember

### ISSUE THREAD

**Issue by xDraxxis** [xDraxxis/XMCDungeons#3]
Enable exact copy in Industrial Forgoing 
Nerf dragon feed
Increase count for dragon steel
Re-add inventory pets

**Comment by xDraxxis** [comment]
Swap helmet and pants recipes

**Comment by xDraxxis** [comment]
Wand of animation mad broken

**Comment by xDraxxis** [comment]
auto jump off

**Comment by xDraxxis** [comment]
Balance Extreme Reactors

**Comment by VoteforShifu** [comment]
ender io or something very similar to transmit power and fluid

**Comment by VoteforShifu** [comment]
make things to work towards, feels too easy to get to the end of meaningful progression

**Comment by VoteforShifu** [comment]
make progression not 100% around ice and fire, but do it by buffing some of the more difficult stuff to get rather than nerfing the dragon stuff

**Comment by VoteforShifu** [comment]
Buff Abyssal Craft stuff, big fun looking mod but kinda garbage loot

**Comment by xDraxxis** [comment]
Lower rate of Infernal mobs spawning

**Comment by xDraxxis** [comment]
Fix various stone gen issues

**Comment by xDraxxis** [comment]
> ender io or something very similar to transmit power and fluid

Done

> make things to work towards, feels too easy to get to the end of meaningful progression

Done

**Comment by xDraxxis** [comment]
> auto jump off



> Balance Extreme Reactors

Both done

**Comment by xDraxxis** [comment]
add hardcore darkness

**Comment by xDraxxis** [comment]
Re-add classic combat

**Comment by VoteforShifu** [comment]
fix cacti

**Comment by xDraxxis** [comment]
Disable Cloak of Virtue in 0.0.5
